lsi: false
highlighter: 'pygments'
markdown: kramdown
exclude:
- 'CNAME'
- 'Gemfile'
- 'Gemfile.lock'
- 'Gruntfile.js'
- 'lib'
- 'package.json'
- 'Rakefile'
- 'README.md'
- 'spec'
- 'Procfile'
- '.sass-cache'
- 'node_modules'
- 'javascripts'

keep_files:
- 'dist'

permalink: pretty

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: :compressed
